// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReinosAcoWebApp.Data;

#nullable disable

namespace ReinosAcoWebApp.Data.Migrations
{
    [DbContext(typeof(ArmaduraDbContext))]
    [Migration("20231127143349_AdicionarDadosIniciaisArmadura")]
    partial class AdicionarDadosIniciaisArmadura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReinosAcoWebApp.Models.Armadura", b =>
                {
                    b.Property<int>("ArmaduraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArmaduraId"));

                    b.Property<int?>("AutenticidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EntregaExpressa")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("ArmaduraId");

                    b.HasIndex("AutenticidadeId");

                    b.ToTable("Armadura");
                });

            modelBuilder.Entity("ReinosAcoWebApp.Models.Autenticidade", b =>
                {
                    b.Property<int>("AutenticidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutenticidadeId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutenticidadeId");

                    b.ToTable("Autenticidade");
                });

            modelBuilder.Entity("ReinosAcoWebApp.Models.Armadura", b =>
                {
                    b.HasOne("ReinosAcoWebApp.Models.Autenticidade", null)
                        .WithMany("Armaduras")
                        .HasForeignKey("AutenticidadeId");
                });

            modelBuilder.Entity("ReinosAcoWebApp.Models.Autenticidade", b =>
                {
                    b.Navigation("Armaduras");
                });
#pragma warning restore 612, 618
        }
    }
}
