// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReinosAcoWebApp.Data;

#nullable disable

namespace ReinosAcoWebApp.Data.Migrations
{
    [DbContext(typeof(ArmaduraDbContext))]
    partial class ArmaduraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ReinosAcoWebApp.Models.Armadura", b =>
                {
                    b.Property<int>("ArmaduraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutenticidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EntregaExpressa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("ArmaduraId");

                    b.HasIndex("AutenticidadeId");

                    b.ToTable("Armadura");
                });

            modelBuilder.Entity("ReinosAcoWebApp.Models.Autenticidade", b =>
                {
                    b.Property<int>("AutenticidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutenticidadeId");

                    b.ToTable("Autenticidade");
                });

            modelBuilder.Entity("ReinosAcoWebApp.Models.Armadura", b =>
                {
                    b.HasOne("ReinosAcoWebApp.Models.Autenticidade", null)
                        .WithMany("Armaduras")
                        .HasForeignKey("AutenticidadeId");
                });

            modelBuilder.Entity("ReinosAcoWebApp.Models.Autenticidade", b =>
                {
                    b.Navigation("Armaduras");
                });
#pragma warning restore 612, 618
        }
    }
}
